<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SqliteXport\SqliteXport.csproj" />
    <ProjectReference Include="..\DB2XL.Query\DB2XL.Query.csproj" />
    <ProjectReference Include="..\DB2XL.DeltaExport\DB2XL.DeltaExport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Spectre.Console" Version="0.50.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
